development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  username: develop
  password: develop
  host: localhost
 
test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  username: test
  password: test
  host: localhost